language: node_js
node_js:
- '5.2'
cache:
  directories:
  - node_modules
before_script:
  - npm i -g mversion
  - git config --global user.email "tusharmath@gmail.com"
  - git config --global user.name "Travis-CI"
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - mversion patch -m
  - git push --all
deploy:
  on:
    branch: master
  provider: npm
  email: tusharmath@gmail.com
  api_key:
    secure: EODNXHDmSaVaG32/iCH0BzPB1hpvoqcG43cwGXOK/6/NVPkdcRZxfkxbiGG/ljVsChTUYqPSGSWVSqsqX5QxRGi5n9wdmjzAc/nKPwMY56gRpPNRXBOzj4tonELzifnAnkyWXNMcHeHj96qOeRjAs7mkJiBhx3xZbg5wo9Ku1zfaE1zVU4gF3tTxYhRwsVLjFbIYkRW8R9kxxmOsBSrjG070xIrLTpGAVfpYIv6uhxcVdbyCT5IaHAid+ut5GOwzic+/5hjRq3Muj9i0B8OLUSrg82MgB3EP2h1or8V9G0wtcy/P2nWRdtmeiYmt+djS+u16z6jgPPG9cv/ZLVm9GUSyFKnWONJM78FbsJrhtmL9o+GgVln5rgzKFpaS/UiqmxSVXzmow0tEh0cAFcp0GpSZnJI7IzewkH46NbgQVGTOOFLOf+CLqBw4oELzb1idAyX1MoKspY+uutx0UqoSqfjx91UhxjuHCIbEIabSykxvfUJRTxXud/kF9WxWae43e2MQaclWkhWcIZvDpqWpSJ20kOi+bv2p+LoacFHs1df/PbyxJsogwePru9i8bk53b/ska2zwHP5JrdPcQK7izwdfDi0+fFcOgBLefb3mc13ObCfEjudfFHqN4jm/kQgNgRL5uDvpqnn0Tt3PFAFrP1UEMZwvraw/c/przm7dg9U=
env:
  global:
    secure: DBYRFbcTHEEThAghKHxUrFNs66zcnQ2QYrHPTTprb6425cZQjVamxlW2crmPpzoFDsd9q7hmZmQADaB5um2tlcsGFixIveoqrW87XonJfndSRZ+83vdfUgKyIUs5gNXoehJpSVmQpwIRP5iRcj9PHssS8c0xYEpWeJPZeNZMqoxiJcPDb5sKP/O5NKrDh3do66+1w5oObNsS3Tn2hjTII+w9HRj+2xykOBIU1HrINuvd2Dytj0glOQg0LEpVJjHCBDtCN+wvcq5OZ9ivOZwf9iZPPwMd1r0BKA+Ot8dAV49Uy0iIngQEB9uhXzRppzu0a9+Kx2ort+x0MjOhZyehXcV/WvWxXNSy+zgk6KEEEeNd7N6CcYRUTrLDnbrpqE4BU22q82UIEvHK2erlsqZIIHJVZ5nM9uJhXncCFkmirV0G3CxunrfLlnYLFv6duohjvmlHPZgRC2gGP4I91IMk5XbYFl+UkWRe1RY1VYJkSB8xotCOpSbtzlK2pg6rRb2EvS+JpLsdGbQV+W6DVMMT/y+0XC07qGfMyFDu+W+yfNXr2BZtYHHLdd9/fgXtXRxICxf/ENtEgMAxCDwL/BbX3/B5mBwszBArp3y1FZhpvc+L24G2tZ5xfX4JI5WFtE6RmHfBw4fe3WmUcj6K6RjKVRxVp+TKRhdzOHv48p+WGwc=
